name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gfortran-10
            shell: bash
          - os: macos-latest
            compiler: gfortran-10
            shell: bash
          - os: windows-latest
            compiler: gfortran
            shell: msys2 {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # - name: Add msbuild to PATH
      #   if: ${{ matrix.os == 'windows-latest' }}
      #   uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: |
          cd src
          make FC=${{ matrix.compiler }}
      - name: Run tests
        run: |
          test/runtests.sh
        shell: bash
